language: java

notifications:
  slack: sixeswild:6j5v7uJhL0MruplJO5FlTu9v

cache:
  directories:
      - $HOME/.gradle

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"