package view;

import javax.swing.*;
import java.awt.*;

public class BuilderApplication extends JFrame
{
    private JPanel builderApplication;
    private BuilderMenuPanel builderMenuPanel;
    private SplashScreen splashScreen;

    public BuilderApplication()
    {
        super("Sixes Wild");
        setContentPane(builderApplication);
        pack();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        ((CardLayout) builderApplication.getLayout()).show(builderApplication, "splash");
        this.setResizable(false);
        this.setTitle("Sixes Wild");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        builderApplication = new JPanel();
        builderApplication.setLayout(new CardLayout(0, 0));
        builderMenuPanel = new BuilderMenuPanel();
        builderApplication.add(builderMenuPanel.$$$getRootComponent$$$(), "menuPanel");
        splashScreen = new SplashScreen();
        builderApplication.add(splashScreen.$$$getRootComponent$$$(), "splash");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return builderApplication;
    }
}
