package view;

import javax.swing.*;
import java.awt.*;

public class PlayerApplication extends JFrame
{
    private JPanel playerApplication;
    private SplashScreen splashScreen;
    private PlayerMenuPanel menuPanel;
    private PlayerLevelSelectPanel playerLevelSelectPanel;

    public PlayerApplication()
    {
        super("Sixes Wild");
        setContentPane(playerApplication);
        pack();
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setVisible(true);
        ((CardLayout) playerApplication.getLayout()).show(playerApplication, "splash");
        this.setResizable(false);
        setSize(new Dimension(500, 600));
        this.setTitle("Sixes Wild");
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        playerApplication = new JPanel();
        playerApplication.setLayout(new CardLayout(0, 0));
        splashScreen = new SplashScreen();
        playerApplication.add(splashScreen.$$$getRootComponent$$$(), "splash");
        menuPanel = new PlayerMenuPanel();
        playerApplication.add(menuPanel.$$$getRootComponent$$$(), "menuPanel");
        playerLevelSelectPanel = new PlayerLevelSelectPanel();
        playerApplication.add(playerLevelSelectPanel.$$$getRootComponent$$$(), "levelSelect");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return playerApplication;
    }
}
