package view;

import model.Game;

import javax.swing.*;
import java.awt.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

public class PlayerApplication extends JFrame
{
    private JPanel playerApplication;
    private SplashScreen splashScreen;
    private PlayerMenuPanel menuPanel;
    private PlayerLevelSelectPanel playerLevelSelectPanel;
    private PlayerPlayPanel playerPlayPanel;
    private Game game;

    public PlayerApplication()
    {
        super("Sixes Wild");
        setContentPane(playerApplication);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        ((CardLayout) playerApplication.getLayout()).show(playerApplication, "splash");
        this.setResizable(false);
        setSize(new Dimension(500, 600));
        this.setLocationRelativeTo(null);
        this.setTitle("Sixes Wild");
        this.game = new Game();
        this.playerPlayPanel.setBoard(this.game.getBoard());

        this.addWindowListener(new WindowListener()
        {
            //Add controllers once window is initialized.
            @Override
            public void windowOpened(WindowEvent e)
            {

            }

            @Override
            public void windowClosing(WindowEvent e)
            {

            }

            @Override
            public void windowClosed(WindowEvent e)
            {

            }

            @Override
            public void windowIconified(WindowEvent e)
            {

            }

            @Override
            public void windowDeiconified(WindowEvent e)
            {

            }

            @Override
            public void windowActivated(WindowEvent e)
            {

            }

            @Override
            public void windowDeactivated(WindowEvent e)
            {

            }
        });
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        playerApplication = new JPanel();
        playerApplication.setLayout(new CardLayout(0, 0));
        splashScreen = new SplashScreen();
        playerApplication.add(splashScreen.$$$getRootComponent$$$(), "splash");
        menuPanel = new PlayerMenuPanel();
        playerApplication.add(menuPanel.$$$getRootComponent$$$(), "menuPanel");
        playerLevelSelectPanel = new PlayerLevelSelectPanel();
        playerApplication.add(playerLevelSelectPanel.$$$getRootComponent$$$(), "levelSelect");
        playerPlayPanel = new PlayerPlayPanel();
        playerApplication.add(playerPlayPanel.$$$getRootComponent$$$(), "playPanel");
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return playerApplication;
    }
}
