package view;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import model.Square;
import model.Tile;

import javax.swing.*;
import java.awt.*;

public class SquareViewPanel
{
    private JPanel squarePanel;
    private JLabel squareNumber;
    private JLabel multiplierLabel;
    private Square currentSquare;

    public SquareViewPanel()
    {
        $$$setupUI$$$();
        this.setSquare(new Square());
    }

    public SquareViewPanel(Square s)
    {
        $$$setupUI$$$();
        this.setSquare(s);
    }

    public void setSquare(Square s)
    {
        this.currentSquare = s;
        refresh();
    }

    public void refresh()
    {
        if (currentSquare.isActive())
        {
            Tile currentTile = this.currentSquare.getTile();
            //TODO: Remove this once actual boards are generated.
            if (currentTile == null)
            {
                int tileNum = 1 + (int) (Math.random() * 6);
                int tileMult = (tileNum == 6) ? 1 : 1 + (int) (Math.random() * 3);
                currentSquare.replace(new Tile(tileNum, tileMult));
            }
            currentTile = this.currentSquare.getTile();
            switch (currentTile.getValue())
            {
                case 1:
                    squarePanel.setBackground(new Color(99, 189, 179)); //1
                    break;
                case 2:
                    squarePanel.setBackground(new Color(207, 169, 102)); //2
                    break;
                case 3:
                    squarePanel.setBackground(new Color(86, 95, 182)); //3
                    multiplierLabel.setForeground(new Color(255, 255, 255));
                    squareNumber.setForeground(new Color(255, 255, 255));
                    break;
                case 4:
                    squarePanel.setBackground(new Color(91, 44, 125)); //4
                    multiplierLabel.setForeground(new Color(255, 255, 255));
                    squareNumber.setForeground(new Color(255, 255, 255));
                    break;
                case 5:
                    squarePanel.setBackground(new Color(120, 0, 50)); //5
                    multiplierLabel.setForeground(new Color(255, 255, 255));
                    squareNumber.setForeground(new Color(255, 255, 255));
                    break;
                case 6:
                    squarePanel.setBackground(new Color(65, 0, 50)); //6
                    multiplierLabel.setForeground(new Color(255, 255, 255));
                    squareNumber.setForeground(new Color(255, 255, 255));
                    break;
                default:
                    squarePanel.setBackground(new Color(65, 0, 50)); //6
                    multiplierLabel.setForeground(new Color(255, 255, 255));
                    squareNumber.setForeground(new Color(255, 255, 255));
                    break;
            }

            squareNumber.setText("" + currentTile.getValue());
            if (currentTile.getMultiplier() != 1)
                multiplierLabel.setText(currentTile.getMultiplier() + "x");
            else
                multiplierLabel.setText(" ");
        } else
        {
            multiplierLabel.setText(" ");
            squareNumber.setText(" ");
            squarePanel.setBackground(new Color(200, 200, 200));
        }
    }

    public Square getSquare()
    {
        return this.currentSquare;
    }

    private void createUIComponents()
    {
        squarePanel = new JPanel();
        squareNumber = new JLabel();
        multiplierLabel = new JLabel();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        createUIComponents();
        squarePanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        squarePanel.setMinimumSize(new Dimension(50, 50));
        squarePanel.setPreferredSize(new Dimension(50, 50));
        squarePanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        squareNumber.setHorizontalAlignment(0);
        squareNumber.setHorizontalTextPosition(0);
        squarePanel.add(squareNumber, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(25, 25), null, 0, false));
        multiplierLabel.setHorizontalAlignment(4);
        multiplierLabel.setHorizontalTextPosition(4);
        squarePanel.add(multiplierLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_EAST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$()
    {
        return squarePanel;
    }
}
